library(RColorBrewer)
#display.brewer.all()
cols <- brewer.pal(10, "Paired")
x=read.table('AU_sum.tsv',header = T)
plot(sort(x$H1,decreasing = T),pch=20,cex=0.4,type = 'l',xlab='Gene number',ylab='AU test p-value',col=cols[1],xlim=c(0,1420),ylim=c(0,1))
lines(sort(x$H2,decreasing = T),col=cols[2])
lines(sort(x$H4,decreasing = T),col=cols[3])
lines(sort(x$H5,decreasing = T),col=cols[4])
lines(sort(x$H7,decreasing = T),col=cols[5])
lines(sort(x$H9,decreasing = T),col=cols[6])
lines(sort(x$H12,decreasing = T),col=cols[7])
lines(sort(x$H15,decreasing = T),col=cols[8])
lines(sort(x$H16,decreasing = T),col=cols[9])
lines(sort(x$H17,decreasing = T),col=cols[10])

abline(h = 0.95,lty=2)

x=read.table('PP_sum.tsv',header = T)
plot(sort(x$H1,decreasing = T),pch=20,cex=0.4,type = 'l',xlab='Gene number',ylab='BIC posterior probability',col=cols[1],xlim=c(0,1420),ylim=c(0,1))
lines(sort(x$H2,decreasing = T),col=cols[2])
lines(sort(x$H4,decreasing = T),col=cols[3])
lines(sort(x$H5,decreasing = T),col=cols[4])
lines(sort(x$H7,decreasing = T),col=cols[5])
lines(sort(x$H9,decreasing = T),col=cols[6])
lines(sort(x$H12,decreasing = T),col=cols[7])
lines(sort(x$H15,decreasing = T),col=cols[8])
lines(sort(x$H16,decreasing = T),col=cols[9])
lines(sort(x$H17,decreasing = T),col=cols[10])
